### ISSUE TITLE
Unable to download YouTube videos.

### ISSUE THREAD

**Issue by NomaanMalick** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#88] opened 2022-04-02 10:37 UTC
This is what I get every time I try to download a YouTube video using the script. 
`[debug] Batch file urls: ['https://www.youtube.com/watch?v=wfHXmLXmwz0']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252 (No ANSI), err cp1252 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.9.12 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'archive.log'
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=wfHXmLXmwz0
[youtube] wfHXmLXmwz0: Downloading webpage
[youtube] wfHXmLXmwz0: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Searching for '(?P<meta_title>.+)' in '%(title)s'
[MetadataParser] Parsed meta_title from '%(title)s': 'THE THREE-BODY PROBLEM | Animated Series | Trailer [Eng Sub]'
[debug] Searching for '(?P<meta_artist>.+)' in '%(uploader)s'
[MetadataParser] Parsed meta_artist from '%(uploader)s': 'Alien Delivery'
[info] Testing format 248
[download] Destination: C:\Users\Nomaan\Downloads\TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection-3.2.2\TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection-3.2.2\scripts\Watch Scripts\Watch on PC Script\tmp6px4bnmy.tmp
[download] 100% of 10.00KiB in 00:00
[info] Testing format 251
[download] Destination: C:\Users\Nomaan\Downloads\TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection-3.2.2\TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection-3.2.2\scripts\Watch Scripts\Watch on PC Script\tmpbra0af4o.tmp
[download] 100% of 10.00KiB in 00:00
[info] wfHXmLXmwz0: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr4---sn-ci5gup-qxak.googlevideo.com/videoplayback?expire=1648916187&ei=eyJIYqfuDdalg8UP56GCgAY&ip=122.173.146.15&id=o-AFzSjd80SXjgvePNWG3LP2yP87aIh4ODdQF3ZdxipLki&itag=248&source=youtube&requiressl=yes&mh=6V&mm=31%2C26&mn=sn-ci5gup-qxak%2Csn-cvh76nez&ms=au%2Conr&mv=m&mvi=4&pl=26&initcwndbps=1605000&vprv=1&mime=video%2Fwebm&gir=yes&clen=12606152&dur=122.920&lmt=1638486860980190&mt=1648894134&fvip=5&keepalive=yes&fexp=24001373%2C24007246&beids=23886213&c=ANDROID&txp=5316224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAN_F8bBtTjGE37yPE4y3YIUqktHfwbpYxHIzIjcdgqwQAiEAyJ4BP0wrm5DlQ756lX8cm35BRnLlYlOr7wW9MWHwKKk%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIbUEyeAz21vxuqZTScTICkuLNNQX15jvTXMihYIc4zBAiEAs1HrkF-xUFfl8m82Wpq_wMcRqd-rys2KRmeTezTBdHA%3D"
[download] Destination: Alien Delivery - 20211121 - THE THREE-BODY PROBLEM _ Animated Series _ Trailer [Eng Sub] [wfHXmLXmwz0].f248.webm
[download]   0.3% of 12.02MiB at  5.02MiB/s ETA 00:02     ERROR: '<' not supported between instances of 'float' and 'str'
Traceback (most recent call last):
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 2638, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 3110, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\YoutubeDL.py", line 2835, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\downloader\common.py", line 453, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\downloader\http.py", line 384, in real_download
    return download()
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\downloader\http.py", line 334, in download
    if speed and speed < (self.params.get('throttledratelimit') or 0):
TypeError: '<' not supported between instances of 'float' and 'str'
`

**Comment by BromTeque** [comment] 2022-04-05 13:25
It's a known issue with YT-DLP. See [this issue](https://github.com/yt-dlp/yt-dlp/issues/2996).

A temporary fix is to revert to version 2022.03.08

**Comment by BromTeque** [comment] 2022-04-05 15:46
A patch has already been applied with [commit 51c22ef](https://github.com/yt-dlp/yt-dlp/commit/51c22ef4e2af966d6100d0d97d9e8019022df8ad). I'm guessing it'll be included in the next release. Although I must admit I find myself slightly frustrated that it was not released as a hotfix. The issue is AFAIK only present in version 2022.03.08.01.

Here are some recommendations on how to circumvent the issue:
- Remove the `--throttled-rate` section from Ghosty's script
- Revert YT-DLP to 2022.03.08
- Apply the patch to YT-DLP manually
- Compile current YT-DLP master
- Wait until YT-DLP 2022.04.x releases.

**Comment by TheFrenchGhosty** [comment] 2022-04-06 01:23
I completely forgot to answer this issue, yes, this is a yt-dlp issue, use 2022.03.08 for now.

**Closed** 2022-04-06 01:23 UTC
